### ISSUE TITLE
hardcoded icon on Mate 18.1

### ISSUE THREAD

**Issue by erikdubois** [linuxmint/mintupload#27] opened 2016-12-10 12:38 UTC
Could you change the reference to the icon in 

/usr/share/applications/mintupload.desktop

from 

Exec=mintupload-manager
**Icon=/usr/share/pixmaps/mintupload/icon.svg**
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
StartupNotify=false
NotShowIn=KDE;

to

**Icon=mintupload**

Last icon that breaks the otherwise great theme.

![upload](https://cloud.githubusercontent.com/assets/10594806/21073416/a8d96c50-bedd-11e6-8e57-06bd2bf23b1a.png)

**Comment by JosephMcc** [comment] 2016-12-10 20:06
I don't understand why you are opening a duplicate of your own issue.

**Closed by JosephMcc** 2016-12-10 20:06 UTC

**Comment by erikdubois** [comment] 2016-12-10 21:08
This is the one on Mate. The other issue is on cinnamon.
Both issues have been persistent for years now. It would be great to see it resolved in linux mint 18.1.
Thanks

**Comment by JosephMcc** [comment] 2016-12-10 21:18
Ah ok. It has nothing to do with the Desktop environment so there is no need for separate issues.
